import React from 'react';
import {StyleSheet, View, Dimensions} from 'react-native';
import {
  verticalScale,
  scale,
  moderateScale,
  ScaledSheet,
  s,
  ms,
  vs,
} from 'react-native-size-matters/extend';
const {height, width} = Dimensions.get('window');
import {themeDefault} from '../../themes';
const styles = ScaledSheet.create({
  wholepage: {
    flex: 1,
    backgroundColor: themeDefault.colors.white,
  },
  mainHeading: {
    alignItems: 'center',
    justifyContent: 'center',
  },
  heading: {
    fontSize: s(30),
    fontFamily: themeDefault.fonts.SFNSDisplayRegular,
  },
  login: {
    justifyContent: 'flex-end',
    flex: 0.9,
  },
  textMargin: {
    marginTop: vs(16),
  },
  logo: {
    height: vs(120),
    width: s(130),
    marginTop: ms(130),
    marginLeft: ms(125),
    marginRight: ms(127),
  },
  mainHead: {
    height: vs(180),
    width: s(180),
    // marginLeft: scale(80),
    // marginRight: scale(49),
    fontSize: vs(30),
    textAlign: 'center',
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: s(18),
    color: themeDefault.colors.black,
  },
  landingBtn: {
    justifyContent: 'center',
    height: s(55),
    width: vs(250),
    backgroundColor: themeDefault.colors.primaryColor,
    marginTop: s(70),
    borderRadius: s(5),
    marginLeft: s(45),
    marginRight: s(45),
    marginBottom: s(0),
    fontFamily: themeDefault.fonts.SFNSTextSemibold,
  },

  btnSubHead: {
    backgroundColor: themeDefault.colors.white,
    textAlign: 'center',
    // marginBottom: scale(70),
    // marginTop: scale(26),
    fontSize: s(14),
    //lineHeight: scale(16),
    color: themeDefault.colors.primaryColor,
    fontWeight: '400',
    fontFamily: themeDefault.fonts.SFNSTextRegular,
  },
  mainView: {
    flex: 1,
    backgroundColor: themeDefault.colors.white,
  },
  mainText: {
    fontSize: s(20),
    textAlign: 'center',
    marginTop: s(80),
    marginLeft: s(100),
    height: vs(54),
    width: s(148),
    fontWeight: '500',
  },
  emailText: {
    marginTop: s(13),

    fontWeight: '500',
  },
  countryCode: {
    flexDirection: 'row',
    justifyContent: 'center',
    borderBottomWidth: 1,
    marginHorizontal: 40,
    borderColor: '#00000033',
    marginTop: s(65),
    marginBottom: s(10),
  },
  numberInput: {
    marginTop: s(12),
    height: vs(21),
    width: s(80),
    color: themeDefault.colors.primaryColor,
    fontSize: s(17),
  },
  t4: {
    fontSize: s(64),
    backgroundColor: '#208efb',
    textAlign: 'center',
    marginTop: s(1),
    marginBottom: s(40),
  },
  t5: {
    fontSize: s(18),
    textAlign: 'left',
    marginLeft: s(90),
    marginTop: s(100),
    borderBottomWidth: s(22),
  },
  t6: {
    height: s(90),
    width: s(90),
    marginLeft: s(45),
    flexDirection: 'row',
  },
  t7: {
    marginTop: scale(1),
    height: verticalScale(37),
    width: scale(300),
  },
  MobileNumber: {
    marginTop: scale(0),
    height: verticalScale(38),
    width: scale(150),
    marginLeft: scale(3),
    fontSize: scale(16),
    fontWeight: '500',
    color: themeDefault.colors.black,
  },
  subView: {
    borderBottomWidth: scale(1),
    height: verticalScale(40),
    marginLeft: scale(45),
    marginRight: scale(60),
    marginTop: scale(1),
    borderColor: '#00000033',
  },
  initialStateColor: {
    backgroundColor: themeDefault.colors.lightBlue,
    fontWeight: 'bold',
    marginTop: 45,
  },
  finalStateColor: {
    backgroundColor: themeDefault.colors.primaryColor,
    fontWeight: 'bold',
    marginTop: 45,
    //#208efb80
  },
  initialState: {
    backgroundColor: themeDefault.colors.lightBlue,
    fontWeight: 'bold',
    marginTop: s(80),
  },
  finalState: {
    backgroundColor: themeDefault.colors.primaryColor,
    fontWeight: 'bold',
    marginTop: s(80),
  },
  animation: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  animationSize: {
    fontSize: 80,
    color: themeDefault.colors.primaryColor,
  },
  animationTitle: {
    fontSize: 24,
    textAlign: 'center',
    color: '#208EFB',
  },

  emailView: {
    flex: 1,
    backgroundColor: '#FFFFFF',
  },
  emailHeading: {
    height: scale(40),
    width: scale(169),
    marginTop: scale(80),
    justifyContent: 'center',
    alignItems: 'center',
    // marginLeft: scale(90),
    fontSize: scale(20),
    fontWeight: '500',
  },
  Tinput: {
    marginLeft: scale(125),
    fontSize: scale(15),
    color: '#7F7F7F',
    marginTop: scale(0),
  },
  Tinput1: {
    marginLeft: scale(125),
    fontSize: scale(15),
    color: '#000000',
    marginTop: scale(0),
  },
  Tview: {
    borderBottomWidth: scale(1),
    marginLeft: scale(30),
    marginRight: scale(40),
    marginTop: scale(6),
    borderColor: '#00000033',
  },
  belowTextInput: {
    marginTop: scale(1),
    fontSize: scale(12),
    marginLeft: scale(70),
    color: themeDefault.colors.lightGrey,
    height: scale(44),
    fontWeight: '500',
    width: scale(400),
  },
  emailSubText: {
    marginTop: scale(10),
    fontSize: scale(12),
    marginLeft: scale(70),
    color: '#A8A8A8',
    height: scale(44),
    fontWeight: '500',
    width: scale(400),
  },
  InputInitialColor: {
    marginLeft: scale(145),
    fontSize: scale(15),
    color: themeDefault.colors.grey,
    marginTop: scale(60),
    fontWeight: '500',
  },
  InputFinalColor: {
    marginLeft: scale(145),
    fontSize: scale(15),
    color: themeDefault.colors.black,
    marginTop: scale(50),
    fontWeight: '500',
  },
  CodeView: {
    flex: 1,
    backgroundColor: themeDefault.colors.white,
  },
  MainHead: {
    height: s(20),
    // width:"100%",
    //marginTop: scale(80),
    // marginLeft: scale(135),
    // marginRight: scale(100),
    // alignItems:'center',
    // justifyContent:"center",
    fontSize: s(20),
    lineHeight: s(24),
    fontWeight: '500',
  },
  CnfmHead: {
    height: s(25),
    //width: "100%",
    //marginLeft: scale(85),
    //marginRight: scale(100),
    fontSize: s(20),
    lineHeight: s(24),
    fontWeight: '500',
  },
  cnfmBtn: {
    textAlign: 'center',
    //marginLeft:65,
    marginTop: 20,
    fontWeight: '500',
  },
  emailLink: {
    fontWeight: '500',
  },
  InputBorder: {
    borderBottomWidth: s(1),
    // marginLeft: scale(55),
    // marginRight: scale(50),
    marginTop: s(6),
    borderColor: '#00000033',
    marginHorizontal: 40,
  },
  InputSubText: {
    marginTop: s(10),
    fontSize: s(12),
    marginLeft: s(70),
    color: themeDefault.colors.lightGrey,
    fontWeight: '500',
  },
  Ttext2: {
    marginTop: s(7),
    fontSize: s(12),
    marginLeft: vs(100),
    color: '#F33C57',
  },
  dummy: {
    backgroundColor: 'black',
  },
  startbtn: {
    fontWeight: '300',
  },
  emailbtn: {},

  initialColor: {
    backgroundColor: '#208efb',
  },
  finalColor: {
    backgroundColor: '#208efb80',
  },
  titleHead: {
    height: scale(48),
    width: scale(160),
    marginTop: scale(80),
    fontSize: scale(19),
    marginRight: scale(1),
    marginLeft: scale(104),
    fontWeight: '500',
  },
  firstTitle: {
    fontSize: scale(20),
    height: scale(23),
    width: '100%',
    marginTop: scale(74),
    //   marginRight:scale(87),
    //   marginLeft:scale(130),
    alignItems: 'center',
    justifyContent: 'center',
    fontWeight: '500',
  },
  secondTitle: {
    marginTop: scale(0),
    fontWeight: '500',
    alignItems: 'center',
    justifyContent: 'center',
    width: '100%',
  },
  primaryTitle: {
    height: scale(25),
    width: '100%',
    //marginLeft:scale(90)
    //justifyContent:'center',

    fontWeight: '500',
  },
  secondaryTitle: {
    width: '100%',
    height: scale(25),
    //marginLeft:scale(51),
    marginTop: scale(0),
    //marginRight:scale(50),
    fontWeight: '500',
  },
  thirdTitle: {
    width: '100%',
    //marginLeft:scale(70),
    marginTop: scale(0),
    //marginRight:scale(50),
    fontWeight: '500',
  },
  PrivacyTitle: {
    fontSize: scale(20),
    height: scale(24),
    width: '100%',

    //   justifyContent:'center',
    //   alignItems:'center',
    marginTop: scale(30),
    //   marginRight:scale(124),
    //   marginLeft:scale(124)
  },
  SubHeadingFirst: {
    fontSize: scale(12),
    //justifyContent:'flex-start',
    alignItems: 'flex-start',
    //height:moderateScale(14),
    //width:'90%',
    //flexDirection:"column",
    color: themeDefault.colors.grey,
    fontWeight: '800',
    marginTop: s(10),
    marginLeft: s(12),
    //   marginRight:scale(12),
  },
  SubText: {
    fontSize: scale(14),
   lineHeight:s(16),
    color: themeDefault.colors.black,
    margin: s(8),
    fontFamily:themeDefault.fonts.SFNSTextRegular
  
  },
  pview: {
    height: moderateScale(50),
    width: scale(250),
    flexDirection: 'row',
  },
  initialText: {
    margin: 7,
    color: themeDefault.colors.black,
  },
  finalText: {
    margin: 7,
    color: themeDefault.colors.grey,
  },
  subview: {
    marginTop: scale(18),
    marginLeft: scale(35),
  },
  //      prvbtn:{
  //         backgroundColor:'green',
  //         height:scale(50),
  //     width:verticalScale(285),
  //    backgroundColor:'#20AFFB',
  //    marginTop:scale(40),
  //    borderRadius:scale(5),
  //    marginLeft:scale(0),
  //    marginRight:scale(100),
  //    marginBottom:scale(3)
  //          },
  initialstate: {
    marginTop: 30,
  },
  finalstate: {
    marginTop: 30,
    backgroundColor: '#208efb80',
  },
  initialTextColor: {
    margin: 7,
    color: '#208efb',
  },
  finalTextColor: {
    margin: 7,
    color: '#208efb80',
  },
  Readyhead: {
    height: scale(58),
    width: scale(212),
    marginTop: scale(310),
    fontSize: scale(24),
    marginRight: scale(1),
    marginLeft: scale(82),
  },
});

export default styles;
